name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v4

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-region: ca-central-1
         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
         role-duration-seconds: 1200

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.6.6

     - name: Terraform init
       working-directory: terraform/chromadb-ecs
       id: init
       run: terraform init

     - name: Terraform format
       working-directory: terraform/chromadb-ecs
       id: fmt
       run: terraform fmt -check

     - name: Terraform validate
       working-directory: terraform/chromadb-ecs
       id: validate
       run: terraform validate

     - name: Terraform Apply
       working-directory: terraform/chromadb-ecs
       id: apply
       run: terraform apply
